# permissions for end users to edit infrastructureproviders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: infrastructureprovider-editor-role
rules:
- apiGroups:
  - machine.crit.sh
  resources:
  - infrastructureproviders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - machine.crit.sh
  resources:
  - infrastructureproviders/status
  verbs:
  - get
